name: Test Release

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build-Extio:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{runner.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source
      # and build directories, but this is only available with CMake 3.13 and higher.
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -G "Visual Studio 16 2019" -A Win32

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE

    - name: Install FFTW3
      working-directory: ${{runner.workspace}}/build
      shell: powershell
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: Invoke-WebRequest -Uri "ftp://ftp.fftw.org/pub/fftw/fftw-3.3.5-dll32.zip" -OutFile fftw-3.3.5-dll32.zip

    - name: Unzip FFTW3
      working-directory: ${{runner.workspace}}/build
      shell: powershell
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: Expand-Archive -Path .\fftw-3.3.5-dll32.zip -DestinationPath unittest

    - name: Create Package
      shell: powershell
      run: Compress-Archive -DestinationPath SDDC_EXTIO.ZIP  -LiteralPath ${{runner.workspace}}/build/ExtIO_sddc/RelWithDebInfo/ExtIO_SDDC.dll,${{runner.workspace}}/build/ExtIO_sddc/RelWithDebInfo/ExtIO_SDDC.pdb,${{runner.workspace}}/build/unittest/libfftw3f-3.dll,README.md
      
    - name: Update Release
      id: update_release
      uses: johnwbyrd/update-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v_test 
        release: Test Release
        files: ./SDDC_EXTIO.ZIP
        draft: false
        prerelease: true
        body: |
          This is a test release which provides the binary built from the latest master.
          
          Target only for early testers. The build may be buggy, crash or even non-functional. It is not suitable for daily use.
          
          The build contains the last commit is:
          ${{github.event.head_commit.message}}
          
